services:
  fsl:
    image: idossha/ti-toolbox_fsl:v6.0.7.18
    platform: linux/amd64
    container_name: fsl_container
    volumes:
      - tit_fsl_data:/usr/local/fsl/
    networks:
      - ti_network
    restart: unless-stopped

  freesurfer:
    image: idossha/ti-toolbox_freesurfer:v7.4.1
    platform: linux/amd64
    container_name: freesurfer_container
    volumes:
      - ti_toolbox_freesurfer_data:/usr/local/freesurfer/
    networks:
      - ti_network
    restart: unless-stopped

  simnibs:
    platform: linux/amd64
    image: idossha/simnibs:2.1.0
    container_name: simnibs_container
    volumes:
      - ti-toolbox_fsl_data:/usr/local/fsl/
      - ti-toolbox_freesurfer_data:/usr/local/freesurfer/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${LOCAL_PROJECT_DIR}:/mnt/${PROJECT_DIR_NAME}
      - ${DEV_CODEBASE_DIR}:/development
    environment:
      USER: root
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_SOFTWARE: "1"
      FSLDIR: /usr/local/fsl
      FSLOUTPUTTYPE: NIFTI_GZ
      FSLMULTIFILEQUIT: "TRUE"
      POSSUMDIR: /usr/local/fsl
      FREESURFER_HOME: /usr/local/freesurfer
      SUBJECTS_DIR: /usr/local/freesurfer/subjects
      FS_LICENSE: /usr/local/freesurfer/license.txt
      LOCAL_PROJECT_DIR: ${LOCAL_PROJECT_DIR}
      PROJECT_DIR_NAME: ${PROJECT_DIR_NAME}
      DEV_CODEBASE_DIR: ${DEV_CODEBASE_DIR}
      DEV_CODEBASE_NAME: ${DEV_CODEBASE_NAME}
      KMP_AFFINITY: "disabled"
    networks:
      - ti_network
    depends_on:
      - fsl
      - freesurfer
    tty: true
    stdin_open: true
    working_dir: /ti-toolbox
    command: ["/bin/bash"]
    restart: unless-stopped

networks:
  ti_network:
    driver: bridge

volumes:
  ti-toolbox_fsl_data:
    external: true
    name: ti-toolbox_fsl_data
  ti-toolbox_freesurfer_data:
    external: true
    name: ti-toolbox_freesurfer_data
