name: Auto Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v2.1.0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract version info
      id: version
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Extract release notes from latest commit message
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Version ${{ steps.version.outputs.version }}
        body: |
          ## 🚀 Temporal Interference Toolbox v${{ steps.version.outputs.version }}
          
          **Automated Release**
          
          ### Changes
          ${{ steps.version.outputs.commit_msg }}
          
          ### Download
          The executables for all platforms will be automatically built and attached to this release within 10-15 minutes.
          
          ### Supported Platforms
          - **macOS**: Universal binary (.app in .zip)
          - **Windows**: 64-bit executable (.exe)
          - **Linux**: AppImage (x86_64)
          
          ---
          
          This release was automatically created by the CI/CD pipeline.
        draft: false
        prerelease: false 