name: Release and Build

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tag pushes

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.9'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.extract_version.outputs.version }}
      release_notes: ${{ steps.extract_version.outputs.release_notes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract version and release notes
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          # Use latest commit message as release notes
          RELEASE_NOTES=$(git log -1 --pretty=%B)
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ steps.extract_version.outputs.version }}
          body: ${{ steps.extract_version.outputs.release_notes }}
          draft: false
          prerelease: false

  build-executables:
    name: Build ${{ matrix.os }} executable
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact-name: TemporalInterferenceToolbox-macOS-universal
            artifact-path: launcher/executable/dist/TI-Toolbox.app
            archive-cmd: 'cd launcher/executable/dist && zip -r ../../../TemporalInterferenceToolbox-macOS-universal.zip TI-Toolbox.app'
            asset-name: TemporalInterferenceToolbox-macOS-universal.zip
            asset-content-type: application/zip
          - os: windows-latest
            artifact-name: TI-Toolbox-Windows
            artifact-path: launcher/executable/dist/TI-Toolbox.exe
            archive-cmd: 'cp launcher/executable/dist/TI-Toolbox.exe TI-Toolbox-Windows.exe'
            asset-name: TI-Toolbox-Windows.exe
            asset-content-type: application/octet-stream
          - os: ubuntu-latest
            artifact-name: TemporalInterferenceToolbox-Linux-x86_64
            artifact-path: launcher/executable/dist/TI-Toolbox
            archive-cmd: 'cp launcher/executable/dist/TI-Toolbox TemporalInterferenceToolbox-Linux-x86_64.AppImage && chmod +x TemporalInterferenceToolbox-Linux-x86_64.AppImage'
            asset-name: TemporalInterferenceToolbox-Linux-x86_64.AppImage
            asset-content-type: application/octet-stream
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-dev \
            python3-venv \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libxrender1 \
            libfontconfig1 \
            libglib2.0-0 \
            libdbus-1-3 \
            xvfb
      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Setting up macOS build environment"
      - name: Update version in code
        shell: bash
        run: |
          VERSION="${{ needs.create-release.outputs.version }}"
          echo "Updating version to: $VERSION"
          sed -i.bak "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" version.py
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" version.py
          sed -i.bak "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" launcher/executable/src/ti_csc_launcher.py
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" launcher/executable/src/ti_csc_launcher.py
          sed -i.bak "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" launcher/executable/src/dialogs.py
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" launcher/executable/src/dialogs.py
      - name: Build executable
        working-directory: launcher/executable
        shell: bash
        env:
          PYTHONIOENCODING: utf-8
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            export PYTHONIOENCODING=utf-8
            export PYTHONUTF8=1
          fi
          if [ -f "docker-compose.yml" ]; then
            echo "✅ docker-compose.yml already exists in build directory"
          elif [ -f "../../docker-compose.yml" ]; then
            echo "Copying docker-compose.yml from project root..."
            cp ../../docker-compose.yml ./
          else
            echo "⚠️  docker-compose.yml not found in either location"
          fi
          python --version
          python -m pip install --upgrade pip
          python build.py
      - name: Verify build output
        shell: bash
        run: |
          if [ -e "${{ matrix.artifact-path }}" ]; then
            echo "✅ Build artifact found: ${{ matrix.artifact-path }}"
          else
            echo "❌ Build artifact not found: ${{ matrix.artifact-path }}"
            exit 1
          fi
      - name: Create archive
        shell: bash
        run: |
          ${{ matrix.archive-cmd }}
      - name: Upload artifact for release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            TemporalInterferenceToolbox-*
            TI-Toolbox-*
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }} 